# Generated by Django 5.2.4 on 2026-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='칼로리(kcal)'),
        ),
        migrations.AddField(
            model_name='post',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_image',
            field=models.ImageField(blank=True, upload_to='nutrition/%Y%m%d', verbose_name='영양성분표 이미지'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='단백질(g)'),
        ),
    ]
