# Generated by Django 5.2.4 on 2026-07-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_calories_post_carbohydrate_post_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=300, verbose_name='해시태그'),
        ),
    ]
