# Generated by Django 4.2.30 on 2026-07-07 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
